[package]
name = "raycast-linux"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "raycast_linux_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-deep-link = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-shell = "2"
freedesktop-file-parser = "0.2.0"
bincode = { version = "2.0.1", features = ["serde"] }
rayon = "1.10.0"
selection = "1.2.0"
url = "2.5.4"
arboard = "3.5.0"
zbus = "5.7.1"
reqwest = { version = "0.12.20", features = ["json", "stream"] }
zip = "4.1.0"
bytes = "1.10.1"
tokio-tungstenite = "^0.27"
futures-util = "^0.3.31"
tokio = { version = "^1.45.1", features = ["full"] }
uuid = { version = "^1.17.0", features = ["v4", "serde"] }
enigo = "0.5.0"
rusqlite = { version = "0.36.0", features = ["bundled"] }
keyring = { version = "3.6.2", features = [
  "apple-native",
  "linux-native",
  "windows-native",
] }
aes-gcm = "0.10.3"
sha2 = "0.10.9"
hex = "0.4.3"
chrono = { version = "0.4.41", features = ["serde"] }
once_cell = "1.21.3"
image = { version = "0.25.6", features = ["png", "ico"] }
regex = "1.11.1"
rand = "0.9.1"
tauri-plugin-http = "2"
trash = "5.2.2"
rdev = "0.5.3"
evdev = "0.13.1"
anyhow = "1.0.98"
lazy_static = "1.5.0"
xkbcommon = "0.8.0"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
walkdir = "2.5.0"
notify = "6.1.1"
notify-debouncer-full = "0.3.1"
percent-encoding = "2.3.1"
tauri-plugin-os = "2"
plist = "1.7.4"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.23"
core-foundation = "0.10"
icns = "0.3.1"
dirs = "6.0.0"
rig-core = { git = "https://github.com/0xPlaygrounds/rig", branch = "main" }
numbat = "1.10.0"
numbat-exchange-rates = "0.5.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"

[dev-dependencies]
tokio = { version = "^1.45.1", features = ["macros", "rt-multi-thread"] }

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"   # rust is not the bottleneck, we can optimize for size with a small performance hit
panic = "abort"
strip = true
